OnlineShop/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Model;
using OnlineShop.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        // we are going to inject both interface to a constructor

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }
        //controller always handles the actions

        //viewResult is used to view the list
        //list is the name of view
        public ViewResult List(string category)
        {
            PieListViewmodel pieListViewModel = new PieListViewmodel();
            if (category == null)
            {
                //view bag is dynamic method and can use to display whatever we want
                //ViewBag.CurrentCategory = "CheeseCake";
                //ViewBag.message = "Can give anything in View Bag";
                //instead of this we can use viewmodel
                //return View(_pieRepository.AllPies.ToList());


                pieListViewModel.pies = _pieRepository.AllPies;
                //pieListViewModel.CurrentCategory = "cheese Cake";
                //data move to the view ie to List
                return View(pieListViewModel);
            }
            else
            pieListViewModel.pies = _pieRepository.AllPies.Where(a => a.Category.CategoryName == category);
            pieListViewModel.CurrentCategory = category;
            //data move to the view ie to List
            return View(pieListViewModel);
        }

        public IActionResult Details(int Id)
        {
            var pie = _pieRepository.GetPieById(Id);
            return View(pie);
        }

    }
}

OnlineShop/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Model;
using OnlineShop.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ShoppingCart _shoppingCart;
        private UserManager<IdentityUser> _userManager;
        public ShoppingCartController(IPieRepository pieRepository, ShoppingCart shoppingCart,UserManager<IdentityUser> userManager)
        {
            _pieRepository = pieRepository;
            _shoppingCart = shoppingCart;
            _userManager = userManager;

        }
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var ShopppingCartViewModel = new ShoppingCartViewModel
            {
               ShoppingCart= _shoppingCart,
               ShoppingCartTotal=_shoppingCart.GetShoppingCartTotal()

            };
            return View(ShopppingCartViewModel);
        }
        // means after doing a operation redirect to a view
        public RedirectToActionResult AddToShoppingCart(int pieId)
        {
            var user = _userManager.Users.FirstOrDefault().Id;
            var selectedPie = _pieRepository.AllPies.FirstOrDefault(p => p.PieId == pieId);
            if (selectedPie!=null)
            {
                _shoppingCart.AddToCart(selectedPie, 1, user);
            }
            // return to Action Index
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromShoppingCart(int pieId)
        {
            var selectedPie= _pieRepository.GetPieById(pieId);
            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }

            return RedirectToAction("Index");
        }
    }
}

OnlineShop/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Css/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
   
    
    <div class="container">
         <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
             <div class="container">

                 <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                         <span class="sr-only">Toggle navigation</span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span>
                         <span class="icon-bar"></span>
                     </button>
                 </div>
                 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     <ul class="nav navbar-nav">
                         <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                         @await Component.InvokeAsync("CategoryMenu")
                         @*<li><a asp-controller="Pie" asp-action="List">Pies</a></li>*@


                         @*call the shooppingcart summaryviewcomponent
        viewcomponent is also has controller like functionality which also call views
        this commonly used if we want to use the functionality in more thna one page eg-shopping cart basket*@

                         @await Component.InvokeAsync("ShoppingCartSummary")
                         <li><a asp-controller="ContactUs" asp-action="Index">ContactUs</a></li>
                         <partial name="_LoginPartial"/>
                     </ul>
                 </div>
             </div>
         </nav>

    <div class="row">
        <div class="col-md-3">
            <p class="lead">
                <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" />
            </p>
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>
    @RenderSection("Scripts", required: false);
</body>
</html>

OnlineShop/Views/Shared/_PieCard.cshtml
@model Pie;
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
    </div>
    <div class="addToCart">
        <p class="button">
            <a class="btn-primary btn" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.PieId">
                AddToCart
            </a>
        </p>

    </div>
</div>